name: pop
description: pop.dart's a set of utility methods and classes to make Dart development intuitive, simple, and readable.
version: 0.1.1
repository: https://github.com/dartsidedev
homepage: https://github.com/vincevargadev
issue_tracker: https://github.com/dartsidedev/pop/issues
environment:
  sdk: '>=2.17.6 <3.0.0'
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
